### ISSUE TITLE
"Only a ReactOwner can have refs"

### ISSUE THREAD

**Issue by Ice32** [frontsideair/react-clockpicker#1]
I have just installed react-clockpicker using npm and I'm getting the following error:

 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Other packages' versions I'm using:
    "react": "^15.1.0",
    "react-bootstrap": "^0.28.4",
    "react-clockpicker": "0.0.4",
    "react-dom": "^15.1.0"

**Comment by frontsideair** [comment]
I'll take a look at this no later than this weekend, we're using this in prod but haven't upgraded packages for a while.

**Comment by Ice32** [comment]
Great, thanks

**Comment by frontsideair** [comment]
Sorry for late reply.

I finally reproduced the issue and will be fixing it asap. The problem is AFAIK react-clockpicker depends on React v0.14.8 and multiple versions of React may cause this error, as noted in the error details page.

**Comment by frontsideair** [comment]
I think v0.1.1 solves your problem. Can you test and tell me if it doesn't work? Thanks.
